//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NavetteEntities : DbContext
    {
        public NavetteEntities()
            : base("name=NavetteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank_cards> bank_cards { get; set; }
        public virtual DbSet<line> lines { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<paypal_accounts> paypal_accounts { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<traveller> travellers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vehicule> vehicules { get; set; }
    }
}
