//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public line()
        {
            this.subscriptions = new HashSet<subscription>();
        }
    
        public int id { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public Nullable<System.TimeSpan> estimated_arrival_time { get; set; }
        public string departure_location { get; set; }
        public string arrival_location { get; set; }
        public string day { get; set; }
        public Nullable<bool> weekly { get; set; }
        public string vehicule { get; set; }
        public Nullable<int> owner_company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscription> subscriptions { get; set; }
        public virtual provider provider { get; set; }
        public virtual vehicule vehicule1 { get; set; }
    }
}
