//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_methods
    {
        public int traveller_id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public int payment_method_id { get; set; }
    
        public virtual bank_cards bank_cards { get; set; }
        public virtual paypal_accounts paypal_accounts { get; set; }
        public virtual traveller traveller { get; set; }
    }
}
