//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int request_id { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public System.TimeSpan estimated_arrival_time { get; set; }
        public string departure_location { get; set; }
        public string arrival_location { get; set; }
        public string day { get; set; }
        public bool weekly { get; set; }
        public int owner_id { get; set; }
    
        public virtual traveller traveller { get; set; }
    }
}
