//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string connectionstring { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public Nullable<bool> approved { get; set; }
        public string name { get; set; }
    
        public virtual provider provider { get; set; }
        public virtual traveller traveller { get; set; }
    }
}
