//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicule()
        {
            this.lines = new HashSet<line>();
        }
    
        public string brand { get; set; }
        public string registration_number { get; set; }
        public string type { get; set; }
        public Nullable<int> seats { get; set; }
        public int provider_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<line> lines { get; set; }
        public virtual provider provider { get; set; }
    }
}
